name: cursin
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.7+107

environment:
  sdk: ">=2.18.0-0 <3.0.0"

dependencies:
  
  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2

  flutter:
    sdk: flutter
    
  fluttertoast: ^8.0.8
  font_awesome_flutter: ^9.0.0
  path_provider: ^2.0.12
  carousel_slider: ^4.0.0
  google_mobile_ads: ^1.2.0
  provider: ^5.0.0
  shared_preferences: ^2.0.7
  shared_preferences_web: ^2.0.2
  url_launcher: ^6.0.10
  url_launcher_web: ^2.0.5
  flutter_user_agentx: ^1.2.4
  rename: ^2.0.1
  flutter_native_splash: ^1.3.3
  flutter_local_notifications: ^9.9.1
  rxdart: ^0.27.3
  timezone: ^0.8.0
  flutter_native_timezone: ^2.0.0
  get: ^4.6.1
  http:
  mailto: ^2.0.0
  flutter_share: ^2.0.0
  share_plus: ^4.0.4
  flutter_webview_pro: ^3.0.1+4
  sqflite: ^2.0.2
  restart_app: ^1.1.0
  percent_indicator: ^4.2.0
  mccounting_text: ^1.0.0
  giff_dialog: ^1.0.1
  cached_network_image: ^3.2.3
  device_info_plus: ^4.0.0
  cron: ^0.5.1
  page_view_indicators: ^2.0.0
  permission_handler: ^10.2.0
  flutter_downloader: ^1.10.2
  riverpod: ^2.3.6
  flutter_riverpod: ^2.3.6
  animate_do: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon/ic_launcher.png"

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/blue_background.jpg
    - assets/icon/icon_logo_no_png.png
    - assets/icon/ic_launcher.png
    - assets/icon/ic_notification.png
    - assets/logo_icon.png
    - assets/gif_open_browser.gif