import 'dart:math';
import 'package:cursin/model/curso_lista_model.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:sqflite/sqflite.dart';
import 'package:path/path.dart';

class DatabaseHandler {
  Future<Database> initializeDB() async {
    String path = await getDatabasesPath();
    return openDatabase(
      join(path, 'courses_tic.db'),
      onCreate: (database, version) async {
        final String sql = ''
            'CREATE TABLE cursos ('
            ' id INTEGER PRIMARY KEY AUTOINCREMENT,'
            ' title TEXT,'
            ' entidad TEXT,'
            ' categoria TEXT,'
            ' emision TEXT,'
            ' imgcourse TEXT,'
            ' urlcourse TEXT,'
            ' idioma TEXT,'
            ' duracion TEXT,'
            ' description TEXT'
            ');';

        await database.execute(sql);

        //'("Curso gratis de ", "Edutin Academy", "Idiomas", "Sin certificado", "", "", "Español", "00 horas","++¡Éxitos en tu capacitación!++El acceso a este curso es gracias a la plataforma que lo emite y a la aplicación de Cursin, la cual indexó y puso a disposición de sus usuarios el acceso a la plataforma web de dicho curso. \n\nEs probable que una vez accedas se te pida inscribirte o registrarte.++Aunque este curso NO CONTIENE un certificado de finalización gratuito, puedes tomarlo y finalizarlo en el momen que lo requieras. Esperamos que le saques el máximo aprovecho a este curso y que mejores tu perfil académico y profesional."),'
        //'("Curso gratis de ", "Fundación Carlos Slim", "TIC", "Con certificado gratis", "img", "url", "Español", "0 horas", "++¡Éxitos en tu capacitación!++El acceso a este curso es gracias a la plataforma que lo emite y a la aplicación de Cursin, la cual indexó y puso a disposición de sus usuarios el acceso a la plataforma web de dicho curso. \n\nEs probable que una vez accedas se te pida inscribirte o registrarte.++Esperamos que le saques el máximo aprovecho a este curso y que mejores tu perfil académico y profesional."),'
        //Aunque este curso NO CONTIENE un certificado de finalización gratuito, puedes tomarlo y finalizarlo en el momento que lo requieras.
        final String addCourse = ''
            'INSERT INTO cursos(title, entidad, categoria, emision, imgcourse, urlcourse, idioma, duracion, description) VALUES '
            //

            '("Curso gratis básico del Universo 3D con SketchUp Pro" , "Techlr", "Artes, TIC", "Con certificado gratis", "https://blogger.googleusercontent.com/img/a/AVvXsEhDGXgDXoSRvCpfKH6SDSYApJ6Q8sQhx2GywXwXl-skW904T2vNysF9d5vwkKF9Mg6jw00TKypMJqrT79W_bdIH6mF4AyJhuXOpJre0jXw3psH02QIXyCbovGThAWvlhJGrppzMn42IMZW0sRpiGEJwVG4FrnFO52UZCKMqYxWekWbPPPOwDjCguMLN", "https://teachlr.com/cursos-online/curso-introduccion-al-universo-3d-con-sketchup/", "Español", "05 horas", "++Este curso nos va a dar las bases para poder introducirnos al 3D con un programa fácil de usar y entender. SketchUp es un programa muy amigable que tiene una curva de aprendizaje muy suave para que los usuarios se concentren en lo que de verdad importa que es ser creativo y no en como usar el programa.\nCon este curso vamos a darnos cuenta lo fácil que puede ser aprender 3D y todo el potencial que tiene en múltiples áreas como la educación, diseño, arte, arquitectura, ingeniería, medicina, ciencia entre otros. ++¡Éxitos en tu capacitación!++El acceso a este curso es gracias a la plataforma que lo emite y a la aplicación de Cursin, la cual indexó y puso a disposición de sus usuarios el acceso a la plataforma web de dicho curso. \n\nEs probable que una vez accedas se te pida inscribirte o registrarte.++Esperamos que le saques el máximo aprovecho a este curso y que mejores tu perfil académico y profesional."),'
            //
            '("Curso gratis de Introducción a Generative AI Studio", "Google Skillshop", "TIC, IA", "Con certificado gratis", "https://blogger.googleusercontent.com/img/a/AVvXsEhljfuSEsot6mdtcNXpa13MbTXmJSM2JHXOFMSGnTYRoTYsjzr6v_3yG45ozO4Z3snCtFoePlLDr8TYKB1u_7EE02wVFA99LTxoACGpX2Q0Aow4XlqNTEa0GN1XlgvbPdyyxajCXV6czS6i4Cys_rFhRcrbD00kiJutQGxUq5wZl4RKIPGU183LJ_3r", "https:www.cloudskillsboost.google/course_templates/552", "Inglés", "3 horas", "Este curso presenta Generative AI Studio, un producto sobre Vertex AI, que lo ayuda a crear prototipos y personalizar modelos de IA generativa para que pueda usar sus capacidades en sus aplicaciones. En este curso, aprenderá qué es Generative AI Studio, sus características y opciones, y cómo usarlo caminando a través de demostraciones del producto. Al final, tendrás un laboratorio práctico para aplicar lo que aprendiste y un cuestionario para poner a prueba tus conocimientos.++Cuando completes este curso, ¡puedes ganar la insignia que se muestra arriba! Vea todas las insignias que ha ganado visitando su página de perfil. ¡Impulse su carrera en la nube mostrando al mundo las habilidades que ha desarrollado!++¡Éxitos en tu capacitación!++El acceso a este curso es gracias a la plataforma que lo emite y a la aplicación de Cursin, la cual indexó y puso a disposición de sus usuarios el acceso a la plataforma web de dicho curso. \n\nEs probable que una vez accedas se te pida inscribirte o registrarte.++Esperamos que le saques el máximo aprovecho a este curso y que mejores tu perfil académico y profesional."),'
            //
            '("Curso gratis de Crear modelos de subtítulos de imágenes", "Google Skillshop", "TIC, IA", "Con certificado gratis", "https://blogger.googleusercontent.com/img/a/AVvXsEiniKI9zFsU_WU0UvP6Iac4-cPt5FDWCqH2ajmSST5fXDpSr7Mqqkyod7vn1jgKul9KjZmJ8AjF8ywvzLWzy9t5qmcDhpQobeEkVVPdVvEXJ-I5Yir2VLHMAigxWXVA8tOCYYV3tzNpHNQjh2XT2bPUScjidjJw1nGyrJ_MXmRCKNJfWhy_bmgDIBGp", "https:www.cloudskillsboost.google/course_templates/542", "Inglés", "3 horas", "Este curso le enseña cómo crear un modelo de subtítulos de imágenes mediante el aprendizaje profundo. Aprenderá sobre los diferentes componentes de un modelo de subtitulado de imágenes, como el codificador y el decodificador, y cómo entrenar y evaluar su modelo. Al final de este curso, podrá crear sus propios modelos de subtítulos de imágenes y usarlos para generar subtítulos para imágenes.++Cuando completes este curso, ¡puedes ganar la insignia que se muestra arriba! Vea todas las insignias que ha ganado visitando su página de perfil. ¡Impulse su carrera en la nube mostrando al mundo las habilidades que ha desarrollado!++¡Éxitos en tu capacitación!++El acceso a este curso es gracias a la plataforma que lo emite y a la aplicación de Cursin, la cual indexó y puso a disposición de sus usuarios el acceso a la plataforma web de dicho curso. \n\nEs probable que una vez accedas se te pida inscribirte o registrarte.++Esperamos que le saques el máximo aprovecho a este curso y que mejores tu perfil académico y profesional."),'
            //
            '("Curso gratis de Modelos de transformadores y modelo BERT", "Google Skillshop", "TIC, IA", "Con certificado gratis", "https://blogger.googleusercontent.com/img/a/AVvXsEjRWQF_1yNBVMg6L8eWjgLWOE1rmWJMkEYm7XrgGO5dCIfODm3XvLjkl0z3BYjYpcAijttER6jsd9jJ6fH5yCxy6hOWsKntkXrsfdNrF7uvtr38jwPnxtF8JAiY9wvZdumgUcFMSkqzQtGS_WSyWFpoHUbg2I_lAOzgAbokHoIhea6ExekC3pOi-2au", "https:www.cloudskillsboost.google/course_templates/538", "Inglés", "3 horas", "Este curso le presenta la arquitectura Transformer y el modelo Bidirectional Encoder Representations from Transformers (BERT). Aprenderá sobre los componentes principales de la arquitectura Transformer, como el mecanismo de autoatención, y cómo se usa para construir el modelo BERT. También aprenderá sobre las diferentes tareas para las que se puede usar BERT, como la clasificación de texto, la respuesta a preguntas y la inferencia de lenguaje natural.Se estima que este curso tardará aproximadamente 45 minutos en completarse.++Cuando completes este curso, ¡puedes ganar la insignia que se muestra arriba! Vea todas las insignias que ha ganado visitando su página de perfil. ¡Impulse su carrera en la nube mostrando al mundo las habilidades que ha desarrollado!\n\n¡Éxitos en tu capacitación!++El acceso a este curso es gracias a la plataforma que lo emite y a la aplicación de Cursin, la cual indexó y puso a disposición de sus usuarios el acceso a la plataforma web de dicho curso. \n\nEs probable que una vez accedas se te pida inscribirte o registrarte.++Esperamos que le saques el máximo aprovecho a este curso y que mejores tu perfil académico y profesional."),'
            //
            '("Curso gratis de Redes Neuronales: Mecanismo de atención", "Google Skillshop", "TIC, IA", "Con certificado gratis", "https://blogger.googleusercontent.com/img/a/AVvXsEgtlyla4XYREL0N9rKmu3_4pm3KdxiZOJ9cwb2qT0jHfT4CY_g6oEBf5W8ycNQXbZRSyzrKfI781lLJDiVwsBYaNIqSiJmHOaFzZrdez-sIG0kbaZo4M4GDrBVTxDE_yYZBLoGMOmQ7nRsMQPw1RIOeMyTM4FdQluEc6evTn_xNrVVwOZAnicida3Xe", "https:www.cloudskillsboost.google/course_templates/537", "Inglés", "3 horas", "Este curso le presentará el mecanismo de atención, una técnica poderosa que permite que las redes neuronales se centren en partes específicas de una secuencia de entrada. Aprenderá cómo funciona la atención y cómo se puede utilizar para mejorar el rendimiento de una variedad de tareas de aprendizaje automático, incluida la traducción automática, el resumen de texto y la respuesta a preguntas.++Se estima que este curso tardará aproximadamente 45 minutos en completarse.++Cuando completes este curso, ¡puedes ganar la insignia que se muestra arriba! Vea todas las insignias que ha ganado visitando su página de perfil. ¡Impulse su carrera en la nube mostrando al mundo las habilidades que ha desarrollado!++¡Éxitos en tu capacitación!++El acceso a este curso es gracias a la plataforma que lo emite y a la aplicación de Cursin, la cual indexó y puso a disposición de sus usuarios el acceso a la plataforma web de dicho curso. \n\nEs probable que una vez accedas se te pida inscribirte o registrarte.++Esperamos que le saques el máximo aprovecho a este curso y que mejores tu perfil académico y profesional."),'
            //
            '("Curso gratis de Arquitectura Encoder-Decoder", "Google Skillshop", "TIC, IA", "Con certificado gratis", "https://blogger.googleusercontent.com/img/a/AVvXsEg4nw5wQBaJ-f93KZ-OYROhseXsWtE7P6Tep9AIaGq0npGiaPMBR3syWOZoQTQdUI_bI4TizxEHal8hQJE7ZEEgkjV7eBYgTXUElHGWwOlVHRTYSwOgTNv8aNxpr1kzHVwin6XDkIwm813r-uTCnjHqz7fcxgBTaz0mOiMqHjRRndZdY5vx-26_uzaW", "https:www.cloudskillsboost.google/course_templates/543", "Inglés", "3 horas", "Este curso le brinda una sinopsis de la arquitectura codificador-decodificador, que es una arquitectura de aprendizaje automático potente y frecuente para tareas de secuencia a secuencia, como traducción automática, resumen de texto y respuesta a preguntas. Aprenderá sobre los componentes principales de la arquitectura codificador-decodificador y cómo entrenar y servir estos modelos. En el tutorial de laboratorio correspondiente, codificarás en TensorFlow una implementación sencilla de la arquitectura codificador-decodificador para la generación de poesía desde el principio.++Cuando completes este curso, ¡puedes ganar la insignia que se muestra arriba! Vea todas las insignias que ha ganado visitando su página de perfil. ¡Impulse su carrera en la nube mostrando al mundo las habilidades que ha desarrollado!++¡Éxitos en tu capacitación!++El acceso a este curso es gracias a la plataforma que lo emite y a la aplicación de Cursin, la cual indexó y puso a disposición de sus usuarios el acceso a la plataforma web de dicho curso. \n\nEs probable que una vez accedas se te pida inscribirte o registrarte.++Esperamos que le saques el máximo aprovecho a este curso y que mejores tu perfil académico y profesional."),'
            //
            '("Curso gratis de Fundamentos de la IA generativa", "Google Skillshop", "TIC, IA", "Con certificado gratis", "https://blogger.googleusercontent.com/img/a/AVvXsEiGh3SkFCiz1uiAiCsXpTRnZbmuIv5aW20cQOPXr9F36UPhkV_gNSixEWHeJTSX2gj5mc37utHxrp_1AQhQSrleFkDGXp8QmzfQHi55q6OQZKonxL4XnAPMlTCGTkG8WHpAz1rTOeP_cTSAMHsSa8wpY1L1LpedDryBawnRuaOPodmpccZjpdVbLH5g", "https:www.cloudskillsboost.google/course_templates/556", "Inglés", "3 horas", "Obtenga una insignia de habilidad completando los cursos Introducción a la IA generativa, Introducción a los modelos de lenguaje grandes e Introducción a la IA responsable. Al pasar el cuestionario final, demostrará su comprensión de los conceptos fundamentales de la IA generativa.Una insignia de habilidad es una insignia digital emitida por Google Skillshop en reconocimiento a su conocimiento de los productos y servicios de Google Skillshop. Comparta su insignia de habilidad haciendo público su perfil y agregándolo a su perfil de redes sociales.\nCuando completes este curso, ¡puedes ganar la insignia que se muestra arriba! Vea todas las insignias que ha ganado visitando su página de perfil. ¡Impulse su carrera en la nube mostrando al mundo las habilidades que ha desarrollado!\n\n¡Éxitos en tu capacitación!++El acceso a este curso es gracias a la plataforma que lo emite y a la aplicación de Cursin, la cual indexó y puso a disposición de sus usuarios el acceso a la plataforma web de dicho curso. \n\nEs probable que una vez accedas se te pida inscribirte o registrarte.++Esperamos que le saques el máximo aprovecho a este curso y que mejores tu perfil académico y profesional."),'
            //
            '("Curso gratis de Introducción a la IA responsable", "Google Skillshop", "TIC, IA", "Con certificado gratis", "https://blogger.googleusercontent.com/img/a/AVvXsEhfxeQL2gYG7badYaY2ZJWtFstkzCe95vKVWzdWQSE_IEFAWqGypc4CM4uKSGUoaedHBHJdgnjUbmc0hcD7dvL4FAst_ToSK8qlqZnVU7yxDHi0TLc74OeJ_ihjeVoOWwQJLSApRUIQVtu_BewK4xMMLA1xnHk1v0C15GxmAMjR64p683k7NdalhbFo", "https:www.cloudskillsboost.google/course_templates/554", "Inglés", "3 horas", "Este es un curso de microaprendizaje de nivel introductorio destinado a explicar qué es la IA responsable, por qué es importante y cómo Google implementa la IA responsable en sus productos. También presenta los 7 principios de IA de Google.\nCuando completes este curso, ¡puedes ganar la insignia que se muestra arriba! Vea todas las insignias que ha ganado visitando su página de perfil. ¡Impulse su carrera en la nube mostrando al mundo las habilidades que ha desarrollado!\n\n¡Éxitos en tu capacitación!++El acceso a este curso es gracias a la plataforma que lo emite y a la aplicación de Cursin, la cual indexó y puso a disposición de sus usuarios el acceso a la plataforma web de dicho curso. \n\nEs probable que una vez accedas se te pida inscribirte o registrarte.++Esperamos que le saques el máximo aprovecho a este curso y que mejores tu perfil académico y profesional."),'
            //
            '("Curso gratis de Introducción a la generación de imágenes", "Google Skillshop", "TIC, IA", "Con certificado gratis", "https://blogger.googleusercontent.com/img/a/AVvXsEj7BLeI9loiDvVEQH-30A-HldjK16jTyly4R95atLzSx5u8f4hoZ3x1jiSqO1eBFFpPwLDc27usDmeKBLafSrHLyrBNe7voYoufIyFgOdS4kqKnzBKjqEAz7FmRaQ3Y18EBTn49EYcNLN8D4C_kUsDAGUQLTgs9iU2GSzayIbrcVCfIE6ESWoXnvULQ", "https:www.cloudskillsboost.google/course_templates/541", "Inglés", "3 horas", "Este curso presenta modelos de difusión, una familia de modelos de aprendizaje automático que recientemente se mostró prometedora en el espacio de generación de imágenes. Los modelos de difusión se inspiran en la física, específicamente en la termodinámica. En los últimos años, los modelos de difusión se hicieron populares tanto en la investigación como en la industria. Los modelos de difusión sustentan muchos modelos y herramientas de generación de imágenes de última generación en Google Skillshop. Este curso le presenta la teoría detrás de los modelos de difusión y cómo entrenarlos e implementarlos en Vertex AI.\nCuando completes este curso, ¡puedes ganar la insignia que se muestra arriba! Vea todas las insignias que ha ganado visitando su página de perfil. ¡Impulse su carrera en la nube mostrando al mundo las habilidades que ha desarrollado!\n\n¡Éxitos en tu capacitación!++El acceso a este curso es gracias a la plataforma que lo emite y a la aplicación de Cursin, la cual indexó y puso a disposición de sus usuarios el acceso a la plataforma web de dicho curso. \n\nEs probable que una vez accedas se te pida inscribirte o registrarte.++Esperamos que le saques el máximo aprovecho a este curso y que mejores tu perfil académico y profesional."),'
            //
            '("Curso gratis de Introducción a los modelos de lenguaje grandes", "Google Skillshop", "TIC, IA", "Con certificado gratis", "https://blogger.googleusercontent.com/img/a/AVvXsEhKWDlFCopjIMBSTPLc-ehMZQtdkzKc3WqwDpxiUaBkw_VjKNMTWtcffUbU2-Bq0bRIbXFwEdg8x5gIeMxvKiYsW1lygRbi8278riUh-sO-yTdPyHId8ulMhICQsKIe15eCemrP3O3VlMksV8U4-VKgT7DVVQR_On2M9rsjEGSLvJ46FT9fFb4qnsaX", "https:www.cloudskillsboost.google/course_templates/539", "Inglés", "2 horas", "Este es un curso de microaprendizaje de nivel introductorio que explora qué son los modelos de lenguaje grande (LLM), los casos de uso donde se pueden utilizar y cómo puede usar el ajuste rápido para mejorar el rendimiento de LLM. También cubre las herramientas de Google para ayudarlo a desarrollar sus propias aplicaciones de IA de generación. Se estima que este curso tardará aproximadamente 45 minutos en completarse.\n\nCuando completes este curso, ¡puedes ganar la insignia que se muestra arriba! Vea todas las insignias que ha ganado visitando su página de perfil. ¡Impulse su carrera en la nube mostrando al mundo las habilidades que ha desarrollado!\n\n¡Éxitos en tu capacitación!++El acceso a este curso es gracias a la plataforma que lo emite y a la aplicación de Cursin, la cual indexó y puso a disposición de sus usuarios el acceso a la plataforma web de dicho curso. \n\nEs probable que una vez accedas se te pida inscribirte o registrarte.++Esperamos que le saques el máximo aprovecho a este curso y que mejores tu perfil académico y profesional."),'
            //
            '("Curso gratis de Introducción a la IA generativa", "Google Skillshop", "TIC, IA", "Con certificado gratis", "https://blogger.googleusercontent.com/img/a/AVvXsEi6qWObuHFei4xXfGbG9lml7YA4aLumEnG-rhNnmb1yjFMrO9H-kf7tzDD3QuyDBA-vfu95Bw5k8HDgGF0yr46DCvS4XJm8xFLyyMF4pcw1DYNYaSJtE7EGJhY86sN3xz_wtmeEwIYbdeerFU5oepgecLIyY21nRab07VSEbZz8CJuPiQ83iK8Id3Rc", "https:www.cloudskillsboost.google/course_templates/536", "Inglés", "2 horas", "Este es un curso de microaprendizaje de nivel introductorio destinado a explicar qué es la IA generativa, cómo se usa y en qué se diferencia de los métodos tradicionales de aprendizaje automático. También cubre las herramientas de Google para ayudarlo a desarrollar sus propias aplicaciones de inteligencia artificial de generación. Se estima que este curso tardará aproximadamente 45 minutos en completarse.\n\n¡Éxitos en tu capacitación!++El acceso a este curso es gracias a la plataforma que lo emite y a la aplicación de Cursin, la cual indexó y puso a disposición de sus usuarios el acceso a la plataforma web de dicho curso. \n\nEs probable que una vez accedas se te pida inscribirte o registrarte.++Esperamos que le saques el máximo aprovecho a este curso y que mejores tu perfil académico y profesional."),'
            //
            '("Curso gratis de Comercio electrónico", "Google Skillshop", "TIC, Administración Negocios y Finanzas", "Con certificado gratis", "https://4.bp.blogspot.com/-tct-R5nK3v4/Wvo-jjSiwcI/AAAAAAAAUqY/FAfLvTROSU8SY8Pwh1JzKBytZtNrCQeuQCLcBGAs/s1600/comercio%2Belectronico%2Bcurso%2Bgratis%2Bgoogle.jpg", "https:skillshop.exceedlms.com/student/collection/787525-ecommerce?sid=7df25594-ae3f-4051-9fac-2366523468fe&sid_i=5", "Español", "40 horas", "Este curso de Google contiene 8 módulos y una duración completa de 40 horas. Transforma un negocio tradicional en un negocio online o lanza al mundo de Internet tu propia idea. Descubre cómo comprar y vender productos y servicios en la red. Rompe fronteras con este curso sin coste y llega a nuevos clientes.++¡Éxitos en tu capacitación!++El acceso a este curso es gracias a la plataforma que lo emite y a la aplicación de Cursin, la cual indexó y puso a disposición de sus usuarios el acceso a la plataforma web de dicho curso. \n\nEs probable que una vez accedas se te pida inscribirte o registrarte.++Esperamos que le saques el máximo aprovecho a este curso y que mejores tu perfil académico y profesional.++Recuerda compartir este curso con los amigos que más lo estén necesitando"),'
            //
            '("Curso gratis de Digitalizacion de tu Negocio con Herramientas de Google", "Google Skillshop", "Administración Negocios y Finanzas, TIC", "Con certificado gratis", "https://blog.groupseres.com/hs-fs/hubfs/AdobeStock_117769244-3.jpeg?width=600&name=AdobeStock_117769244-3.jpeg", "https:learndigital.withgoogle.com/activate/course/get-business-online", "Español", "05 horas", "+Si estás pensando en digitalizar tu pequeño negocio, este es el momento perfecto para dar los primeros pasos. ++En este curso básico y muy práctico conocerás el funcionamiento de herramientas como Perfil de Empresa (antiguo Google My Business), YouTube o Google Forms. ++Te acompañaremos paso a paso para que tu negocio sea visible en Internet y lograr que tus productos y servicios lleguen a más clientes.++El acceso a este curso es gracias a la plataforma que lo emite y a la aplicación de Cursin, la cual indexó y puso a disposición de sus usuarios el acceso a la plataforma web de dicho curso. \n\nEs probable que una vez accedas se te pida inscribirte o registrarte.++Esperamos que le saques el máximo aprovecho a este curso y que mejores tu perfil académico y profesional."),'
            //
            '("Curso gratis de Cloud Computing", "Google Skillshop", "TIC", "Con certificado gratis", "https://i.ytimg.com/an/RWgW-CgdIk0/1e7946cf-a0d3-4678-8c35-d75563293b23_mq.jpg?v=5afed46a", "https:skillshop.exceedlms.com/student/collection/786255-cloud-computing?sid=7df25594-ae3f-4051-9fac-2366523468fe&sid_i=1", "Español", "40 horas", "¿Sabes qué beneficios aporta el uso de la tecnología Cloud Computing a un proyecto? Descubre a lo largo de este curso sin coste cómo transformar un negocio e innovar dentro de tu empresa a la vez que reduces sus costes. Además, aprende cómo tener acceso a tu información en cualquier dispositivo y de forma segura.++¡Éxitos en tu capacitación!++El acceso a este curso es gracias a la plataforma que lo emite y a la aplicación de Cursin, la cual indexó y puso a disposición de sus usuarios el acceso a la plataforma web de dicho curso. \n\nEs probable que una vez accedas se te pida inscribirte o registrarte.++Esperamos que le saques el máximo aprovecho a este curso y que mejores tu perfil académico y profesional.")';
        //
        await database.execute(addCourse);
        //await database.execute(addCourse concat addCourse2);

        //deleteOldDatabases();
      },
      version: 1,
    );
  }

  Future<List<curso>> coursesTIC() async {
    final db = await initializeDB();
    final List<Map<String, dynamic>> queryResult =
        await db.rawQuery('SELECT * FROM cursos');
    Map<String, dynamic> result = {};
    for (var r in queryResult) {
      result.addAll(r);
    }
    return queryResult.map((e) => curso.fromMap(e)).toList();
  }
}
